#!/usr/bin/env python3
"""Reads coldcascade/results/oct10_replay.csv (read-only) and writes src/tape.ts:
one array per column the film needs, one entry per minute, USD units."""
import csv, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "coldcascade" / "results" / "oct10_replay.csv"
OUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "tape.ts"
MINUTES = 41
rows = list(csv.DictReader(open(SRC)))[:MINUTES]
px = lambda k: [int(r[k]) / 10 for r in rows]           # raw HyperCore -> USD (BTC szDecimals 5)
usd = lambda k: [int(r[k]) for r in rows]
cols = {
    "bid": px("bid"), "ask": px("ask"), "mark": px("mark"), "oracle": px("oracle"),
    "deskBid": px("deskBid"), "deskAsk": px("deskAsk"),
    "lean": [int(r["lean"]) for r in rows],
    "disl": [int(r["dislocationBps"]) for r in rows],
    "mapBelow": usd("mapBelowNtl"), "mapAbove": usd("mapAboveNtl"),
    "forcedSell": usd("forcedSellNtl"), "forcedBuy": usd("forcedBuyNtl"),
    "absorbedDesk": usd("absorbedDeskNtl"),
    "lvrDesk": usd("lvrDeskNtl"), "lvrControl": usd("lvrControlNtl"), "lvrHard": usd("lvrHardNtl"),
    "lvrPegged": usd("lvrPeggedNtl"), "absorbedPegged": usd("absorbedPeggedNtl"),
    "arbPegged": usd("arbPeggedNtl"), "pnlPegged": [int(r["pnlPeggedBps"]) for r in rows],
}
# The desk's fill price against three references, USD, known at the fill. Kept as data so the
# film can switch reference with one constant; none is a markout.
def captured(ref):
    out = []
    for r in rows:
        a = int(r["absorbedDeskNtl"]); lean = int(r["lean"])
        if not a:
            out.append(0.0); continue
        bid, ask, orc = int(r["bid"]) / 10, int(r["ask"]) / 10, int(r["oracle"]) / 10
        mid = (bid + ask) / 2
        if lean == 2:
            p = int(r["deskAsk"]) / 10; q = {"touch": ask, "mid": mid, "oracle": orc}[ref]; out.append(round(a * (p - q) / p, 2))
        else:
            p = int(r["deskBid"]) / 10; q = {"touch": bid, "mid": mid, "oracle": orc}[ref]; out.append(round(a * (q - p) / p, 2))
    return out
cols["capturedTouch"] = captured("touch")
cols["capturedMid"] = captured("mid")
cols["capturedOracle"] = captured("oracle")
with open(OUT, "w") as f:
    f.write("// Generated by scripts/tape.py from coldcascade/results/oct10_replay.csv. Do not edit.\n")
    f.write(f"export const T0 = {rows[0]['t']}; // unix seconds, minute open of the first row\n")
    f.write(f"export const MINUTES = {MINUTES};\n")
    f.write("export const TAPE = {\n")
    for k, v in cols.items():
        f.write(f"  {k}: [{', '.join(str(x) for x in v)}],\n")
    f.write("};\n")
print("wrote", OUT, "rows", len(rows), "t0", rows[0]["t"])
