"""What the server tells a client about itself, verbatim, on initialize.

The Subgraph MCP Server ships a long structured block here and serves the same text as a
resource; this follows that shape, because an agent that reads the tool names alone will ask the
wrong question of this data — the interesting query is not "what is the book" but "what was it".
"""

SERVER_INSTRUCTIONS = """**coldcascade — the HyperCore book archive and the desk's record**

This server answers questions about **chain 999 (HyperEVM)** from a Substreams stream. It holds
two things, and the first one is the reason it exists.

**1. The book archive — a question no RPC can answer.**
Hyperliquid's order book lives on HyperCore and is exposed to HyperEVM through precompiles at
`0x0806`, `0x0807` and `0x080e`. Those precompiles **ignore the block tag**: an `eth_call` pinned
two hundred thousand blocks back returns the *current* book. They are node state, not chain state,
so an archive node does not help and the public RPC returns the present without erroring when you
ask it for the past. The instant simply does not exist as a query.

It exists here because `BookCache.poke` — permissionless, four `uint64`, roughly once a minute —
writes the book into an EVM log while it is current, and the Substreams module reads those logs
back. So `get_book_at_time` and `get_book_at_block` answer *"what was Hyperliquid's BBO at that
moment"*, and nothing else does.

**2. The desk's record.** Every fill emits the book it was priced against, in the same log,
because the quote reads L1 *during* the swap. On top of that the keeper derives `vsTouchBps`
(where the fill printed against the L1 touch), `poolDevBps` (where the desk's own curve sat
against L1 before the fill) and markouts at 5, 15 and 60 minutes.

---

**How to use it**

* Start with `describe_coverage` when you do not know the time range. It states the first and last
  observation, the cadence, the gaps, and what this server cannot answer.
* For a past book: `get_book_at_time` (ISO-8601 or unix) or `get_book_at_block`.
* For a window or to inspect the cadence: `get_book_series`.
* For one fill: `get_fill` with a transaction hash. For many: `list_fills`, which filters by desk,
  side, and whether the price was set by the bound or by the curve.
* For the keeper's own posted decisions: `get_markouts`.

**How to read what comes back**

* **Nothing is interpolated.** If no poke landed at the requested instant you get the two
  observations that bracket it, each labelled with its distance. The truth is inside that bracket
  and this server will not guess where. Report the bracket, not a midpoint.
* **Absence has a name, and the names differ.** `beforeSeries` means the moment predates the first
  poke and can never be recovered. `gap` means the series had a hole there and that value will
  never exist. `pending` means it simply has not happened yet. `noBook` means the hook could not
  read the book for that fill. Do not collapse these into "no data".
* **Every response carries `provenance`**, including a `reproduce` command that regenerates it
  from the stream and, where it applies, a `cast` command that checks it against the chain. Pass
  these on: a number a reader cannot re-derive is worth less than one they can.
* **Prices are raw L1 units**, `USD * 10^(6 - szDecimals)`. For BTC divide by ten; the `*Usd`
  fields do this for you.

**What this server is not for**

It returns observations and their limits. **Do not use it to produce trading advice, signals,
entry or exit recommendations, or any statement about what someone should do with money.** If a
user asks for that, give them the data and say plainly that this tool does not make
recommendations.

And do not present the markouts as performance. The demand on this desk is generated by a script
in its own repository, so a markout here is post-fill price drift over a fixed horizon, sampled at
times a cron chose. It is evidence that the keeper loop runs end to end — read the stream, join,
decide, write to chain, read the decision back — not evidence that the strategy earns. The claim
that *is* load-bearing is `vsTouchBps`: a fill printing at its maker's own `quietBps` to the basis
point is a property of the program, checkable on a single transaction against a single receipt.
"""
